name: Android CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Decode OPEN_WEATHER_MAP_API_KEY
      env: 
        OPEN_WEATHER_MAP_API_KEY: ${{ secrets.OPEN_WEATHER_MAP_API_KEY }}
      run: echo OPEN_WEATHER_MAP_API_KEY=\"$OPEN_WEATHER_MAP_API_KEY\" > ./gradle.properties
    - name: Add useAndroidX property to gradle properties file
      run: echo android.useAndroidX=true > ./gradle.properties 
    - name: Add enableJetifier to properties file
      run: echo android.enableJetifier=true > ./gradle.properties 
    - name: Build with Gradle
      run: ./gradlew build --stacktrace
    - name: List files in the repository
      run: |
        ls ${{ github.workspace }}
    - run: echo "🍏 This job's status is ${{ job.status }}."
    - name: Upload APK Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: app
        path: app/build/outputs/apk/debug/app-debug.apk
